---
- name: copy
  hosts: test-server
  become: true
  become_user: root
  gather_facts: true
  tasks:
     - name: copy file
       copy: src=/home/ubuntu/website/index.html dest=/var/www/html/index.html
